# Generated by Django 4.0.3 on 2022-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('article', models.TextField(default='Empty')),
                ('caption', models.TextField(default='Empty')),
                ('year', models.TextField(default='Empty')),
                ('month', models.TextField(default='Empty')),
                ('day', models.TextField(default='Empty')),
            ],
            options={
                'db_table': 'article_3',
            },
        ),
    ]
