# Generated by Django 4.0.3 on 2022-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_id', models.DecimalField(decimal_places=2, max_digits=5)),
                ('article', models.TextField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
